### ISSUE TITLE
Error in { : task 1 failed - "object 'p' not found"

### ISSUE THREAD

**Issue by mikkelkrogsholm** [laecdtu/C19DK#3]
I get this error when I run SSEIH.R

`Error in { : task 1 failed - "object 'p' not found"`

It happens when I run this line:

`feRet <- foreach(scenario=idScenarier, .packages = c("data.table", "deSolve")) %dopar%`

Here is my session info:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] doParallel_1.0.15 iterators_1.0.12  foreach_1.4.7     data.table_1.12.6 deSolve_1.28     

loaded via a namespace (and not attached):
[1] compiler_3.6.1   tools_3.6.1      codetools_0.2-16
```

**Comment by jlouis** [comment]
https://github.com/jlouis/C19DK/tree/cleanup-1 fixes some of this.

The underlying problem is that R uses lexical scoping, more or less, but the value `p` isn't in scope inside the wrapper function `nll3w`. It is more safe to create a function with access to the right `p` and `j`, so that is what I did. I also unpacked values from the `p` (named) vector rather than taking the global variables and using those.

I have a hunch these models were run with those values in scope. But of course there is the risk of picking the wrong older variant of `p` in this case.

With those fixes in place, we end up with incorrect dimensionality in `beta[i,]`, which I attribute to the fact we don't have the correct data.

My main worry is also `set.seed(1234)` which means all the `runif(...)` functions will pack the same value for each CPU/Region/Scenario triple. This might be what you want, but my spider sense in parallel programming is tingling since you risk not being random enough when you run your scenarios.

**Comment by laecdtu** [comment]
Thank you for the cleanup.
We were aware of the scoping - but didn't get to make a nice fix before the deadline. You solution is different from what we did in a couple of of ways. I like the way that you make a function to define the wrapper function in the right scope. 
The problem with the dimension of `beta` is that it is a 2x2 matrix and the dimension is dropped when concatenated to the vector `p`. My solution to this is to make `p` a list.
The last part is about the seed. Yes, it is reset to the same seed in each scenario. That is anticipated as it means that all scenarios are evaluated with the same parameters for all but the scenario specific betas. This allows for a more fair comparison of the scenarios as the only difference is the scenario specific parameters. (In this particular case the parameters concerning the period where data is used for the optimization are the same for all scenarios so we could have saved some CPU cycles by only doing the optimization once - however that will not always be the case so we picked a safer way.)
I'll make an update inspired by @jlouis (in the coming week) and check that it runs in a clean environment.

**Comment by mikkelkrogsholm** [comment]
If it is no too much of a hassle, may I suggest that you make it run in one of the R-docker containers (https://www.rocker-project.org/) so that we all share the same infrastructure when running the code?

**Comment by laecdtu** [comment]
We have to run the current code inside [Forskermaskinen](https://sundhedsdatastyrelsen.dk/da/forskerservice/forskermaskinen). We do not have access to docker there and I do not have experience with R-docker. So sorry, it is too much of a hassle right now.

**Comment by jlouis** [comment]
I have a question, I'm dying to know, so I'm hijacking this once again. In the model we have

```
           dS = - nyeSmittede,

           dE1 =  nyeSmittede - 3*gammaEI1*E1,
           dE2 =                3*gammaEI1*E1 - 3*gammaEI1*E2,
           dE3 =                                3*gammaEI1*E2 - 3*gammaEI1*E3,
```

And likewise for the infected groups. Why do we have 3 stages here? My best guess is that since `gammaEI1` is statically held throughout the DiffEq, we need to introduce some "chaos" back in the model. And by staging, the population arrives a bit more haphazardly to the next "real" stage.

The scoping fix is based on an idea that goes back to the 1930'es: namely partial application of functions.

And as for the seed: sound argumentation. You probably want to lock it down then, as randomness if often something you want to control in simulations.

My branch has a nix-expression which can build an environment suitable for running the code. It could be made into a docker container. One might argue that Forskermaskinen should have been based on Docker in the first place, but with some kind of limited repository from which to create containers. t'll probably happen in about 10 years when everyone is using something different :P

**Comment by laecdtu** [comment]
The reason for splitting the latent (and the infected) state in 3 stages has nothing to do with randomness although I'll use probability theory to explain:
If there is on stage in E then the waiting time in the latent state follows an exponential distribution. That means that a large proportion will have a short duration of the latent period and others a very long duration. Having three stages results in Erlang(3) distributed waiting times which have a smaller variance. I've illustrated it with the following example with a mean waiting time of 4 days:
```
q <- seq(0,14,0.1)
plot(q,pexp(q=q, rate = 1/4), type="l",ylab="pdf", xlab="Time in state [days]") #Exponential
lines(q,pgamma(q=q, shape=3,rate = 3/4), col=2)   # Erlang
```

**Comment by jlouis** [comment]
Thank you for the answer. It does make sense to reel in the variance a bit from my point of view compared to the exponential distribution.

**Comment by laecdtu** [comment]
The code is updated so that 'p' is now a list 'pl' and other details. This is the version of the code that was used on May 20th.
I expect that SSI will have approval to share the data in the coming week. I'll share it here when available from SSI.
